shell /bin/zsh
background_opacity 0.8
background_blur 40
background #1f1f1f
foreground #abb2bf
cursor #abb2bf
cursor_text_color #1f1f1f
# background #1f1f1f
# background #fdf6e3
# background #fffdf7
hide_window_decorations yes
tab_bar_edge top
font_size 14.0
map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
