shell /bin/zsh
background_opacity 0.8
background_blur 40
background #1f1f1f
foreground #abb2bf
cursor #abb2bf
cursor_text_color #1f1f1f
# background #1f1f1f
# background #fdf6e3
# background #fffdf7
hide_window_decorations yes
tab_bar_edge top
active_tab_background #4a4a4a
active_tab_foreground #abb2bf
inactive_tab_background #2e2e2e
inactive_tab_foreground #888888
tab_bar_background #1f1f1f
font_size 14.0
map alt+1 no_op
map alt+2 no_op
map alt+3 no_op
